### ISSUE TITLE
Versions in the requirements

### ISSUE THREAD

**Issue by gkiar** [ABCD-STUDY/nda-abcd-s3-downloader#6]
I was wondering if specific versions listed in the requirements file were intentionally fixed? I.e., is this version of pandas

https://github.com/ABCD-STUDY/nda-abcd-s3-downloader/blob/d57585d63f190b922953b1acfd7c6361d71a0fd0/requirements.txt#L11

specifically necessary for this tool to run? I have a much newer version and trying to uninstall it for this old version causes my computer to choke due to version incompatibilities with the newer versions of Python.

Similarly, if this requirement could be loosened, could the same be applied broadly to others?

**Comment by perronea** [comment]
No I haven't run into any issues with newer versions of pandas. It's more of a recommendations.txt than a requirements.txt. That said we do like to keep our software up to date, so if you run into issues with a newer version of a python package please open another issue and we will work on updating the repository accordingly.
